clear all;
clc;

%% =========================
% System Parameters
%% =========================
Nt = 32;
fc = 100e9;
B = 3e9;
tau = 10e-9;

SNR_dB_list = -10:5:20;
Num_SNR = length(SNR_dB_list);

DFT = (1/sqrt(Nt)) * ...
      exp(-1i*pi*[0:Nt-1]' * ...
      (-(Nt-1)/2:(Nt-1)/2) * (2/Nt));

%% =========================
% OMP Parameters
%% =========================
G = 4*Nt;      % Dictionary size
L = 1;         % Single-path channel

%% =========================
% Monte Carlo Parameters
%% =========================
num_iter = 600;
theta_range = [-1,1];

%% =========================
% Result Initialization
%% =========================
NMSE_LS_linear   = zeros(num_iter, Num_SNR);
NMSE_MMSE_linear = zeros(num_iter, Num_SNR);
NMSE_OMP_linear  = zeros(num_iter, Num_SNR);
NMSE_OMP_IGW_linear  = zeros(num_iter, Num_SNR);
NMSE_BT_linear = zeros(num_iter,Num_SNR);


%% =========================
% Monte Carlo Simulation
%% =========================
parfor snr_idx = 1:Num_SNR

    SNR_dB = SNR_dB_list(snr_idx);

    fprintf('SNR = %.2f dB [%d/%d]\n', ...
            SNR_dB, snr_idx, Num_SNR);

    for iter = 1:num_iter

        %% Generate random channel

        theta = theta_range(1) + ...
               (theta_range(2)-theta_range(1))*rand;
%         disp(theta)

        [~, hc] = far_field_channel( ...
                    Nt,...
                    fc,...
                    B,...
                    1,...
                    tau,...
                    theta);

         hc = hc / norm(hc,'fro') * sqrt(Nt);

        %% LS

        [h_LS,~,~,~] = ...
            LS_Channel_Estimation( ...
            hc,...
            Nt,...
            DFT,...
            SNR_dB);

        %% MMSE

        [h_MMSE,~,~,~] = ...
            MMSE_Channel_Estimation( ...
            hc,...
            Nt,...
            DFT,...
            SNR_dB);

        %%BT

        [h_ES, ES_beam, ES_gain, ES_rate] = Far_Field_Exhaustive_Training(hc, DFT, SNR_dB);
        

        %% OMP

        [h_OMP, w_OMP, OMP_gain, OMP_rate] = ...
    OMP_Channel_Estimation(...
    hc, Nt, DFT, SNR_dB, G, L);

        [h_OMP_IGW, ~, ~, ~] = ...
    OMP_IGW_Channel_Estimation(...
    hc, Nt, DFT, SNR_dB, G, L);

        %% NMSE

        norm_h_sq = norm(hc,'fro')^2;

        NMSE_LS_linear(iter,snr_idx) = ...
            norm(hc-h_LS,'fro')^2 / norm_h_sq;

        NMSE_MMSE_linear(iter,snr_idx) = ...
            norm(hc-h_MMSE,'fro')^2 / norm_h_sq;

        NMSE_OMP_linear(iter,snr_idx) = ...
            norm(hc-h_OMP,'fro')^2 / norm_h_sq;

        NMSE_OMP_IGW_linear(iter,snr_idx) = ...
            norm(hc-h_OMP_IGW,'fro')^2 / norm_h_sq;

        NMSE_ES_linear(iter,snr_idx) = ...
            norm(hc-h_ES,'fro')^2 / norm_h_sq;

    end
end

%% =========================
% Average NMSE
%% =========================

mean_NMSE_LS_dB = ...
    10*log10(mean(NMSE_LS_linear,1)+eps);

mean_NMSE_MMSE_dB = ...
    10*log10(mean(NMSE_MMSE_linear,1)+eps);

mean_NMSE_OMP_dB = ...
    10*log10(mean(NMSE_OMP_linear,1)+eps);

mean_NMSE_OMP_IGW_dB = ...
    10*log10(mean(NMSE_OMP_IGW_linear,1)+eps);

mean_NMSE_ES_dB = ...
    10*log10(mean(NMSE_ES_linear,1)+eps);

%% =========================
% Theoretical Bounds
%% =========================

SNR_linear = 10.^(SNR_dB_list/10);

sigma2 = 1 ./ SNR_linear;

% LS theory
NMSE_LS_theory_dB = -SNR_dB_list;

% MMSE theory
NMSE_MMSE_theory_dB = ...
    10*log10( sigma2 ./ (1 + sigma2) );
%% =========================
% Plot
%% =========================

figure;

plot(SNR_dB_list,...
     mean_NMSE_LS_dB,...
     'bo-',...
     'MarkerFaceColor','w',...
     'LineWidth',1.6,...
     'MarkerSize',7);
hold on;

plot(SNR_dB_list,...
     mean_NMSE_MMSE_dB,...
     'rs-',...
     'MarkerFaceColor','w',...
     'LineWidth',1.6,...
     'MarkerSize',7);

plot(SNR_dB_list,...
     mean_NMSE_OMP_dB,...
     'gd-',...
     'MarkerFaceColor','w',...
     'LineWidth',1.6,...
     'MarkerSize',7);

plot(SNR_dB_list,...
     mean_NMSE_OMP_IGW_dB,...
     'color', [1.00,0.41,0.16], ...
     'Marker', '^', ...
     'MarkerFaceColor','w',...
     'LineWidth',1.6,...
     'MarkerSize',7);

plot(SNR_dB_list,...
     NMSE_LS_theory_dB,...
     'k--',...
     'LineWidth',1.5);

plot(SNR_dB_list,...
     NMSE_MMSE_theory_dB,...
     'm:',...
     'LineWidth',1.6);

plot(SNR_dB_list,...
     mean_NMSE_ES_dB,...
     'cv-',...
     'MarkerFaceColor','w',...
     'LineWidth',1.6,...
     'MarkerSize',7);

grid on;
% box on;

xlabel('SNR (dB)',...
       'Interpreter','latex',...
       'FontSize',12);

ylabel('NMSE (dB)',...
       'Interpreter','latex',...
       'FontSize',12);

legend('LS',...
       'MMSE',...
       'OMP',...
       'OMP-IGW',...
       'LS Theory',...
       'MMSE Theory',...
       'Exhaustive BT', ...
       'Location','southwest',...
       'Interpreter','latex',...
       'FontSize',11);

% title('Channel Estimation NMSE versus SNR');

% set(gca,...
%     'FontSize',12,...
%     'LineWidth',1.2);
